resetView = true
startAtTradingWarehouse = false
StartAtTradingWarehouseAndMergeScroll = false
startAtCallPlace = true
useWarehouseMaid = true
repairWeapons = true
backExchange = true
intoHutton = false
inHutton = false
enableEmailAlarm = false
email = ""
skill_config = "[{\"groupName\": \"技能组1\", \"groupExpectCost\": 3.75, \"blocks\": [{\"name\": \"强：蝶旋风\", \"pipelines\": [{\"type\": \"KBPress\", \"key\": \"left shift\"}, {\"type\": \"MSClick\", \"key\": \"left\"}, {\"type\": \"KBRelease\", \"key\": \"left shift\"}, {\"type\": \"wait\", \"sec\": 1.4}]}, {\"name\": \"强：飓风\", \"pipelines\": [{\"type\": \"KBPress\", \"key\": \"space\"}, {\"type\": \"wait\", \"sec\": 1}, {\"type\": \"KBRelease\", \"key\": \"space\"}, {\"type\": \"wait\", \"sec\": 0.5}]}]}, {\"groupName\": \"技能组2\", \"groupExpectCost\": 8, \"blocks\": [{\"name\": \"霸体：左移动\", \"pipelines\": [{\"type\": \"KBPress\", \"key\": \"left shift\"}, {\"type\": \"KBPressAndRelease\", \"key\": \"D\"}, {\"type\": \"KBRelease\", \"key\": \"left shift\"}, {\"type\": \"wait\", \"sec\": 0.75}]}, {\"name\": \"霸体：右移动\", \"pipelines\": [{\"type\": \"KBPress\", \"key\": \"left shift\"}, {\"type\": \"KBPressAndRelease\", \"key\": \"A\"}, {\"type\": \"KBRelease\", \"key\": \"left shift\"}, {\"type\": \"wait\", \"sec\": 0.75}]}, {\"name\": \"强：骤雨\", \"pipelines\": [{\"type\": \"KBPress\", \"key\": \"left shift\"}, {\"type\": \"KBPressAndRelease\", \"key\": \"Q\"}, {\"type\": \"KBRelease\", \"key\": \"left shift\"}]}]}]"
boss1CanBeHitCoolTime = 36.5
boss2CanBeHitCoolTime = 12.0
skillGroup1KillBoss1Cost = 1.5
backTradingHouseTime = 140.0
collectImgTaskOver = false
collectImgBagUI = false
collectImgProcessBar = false
collectImgMargram = false
collectImgKhalk = false
collectImgUseWarehouseMaid = false
collectImgFindNPC = false
collectImgGMCheck = true
useWarehouseMaidShortcut = "1"
setTentShortcut = "3"
tentRepairWeaponsShortcut = "4"
recycleTentShortcut = "5"
