[app]
max_process_cnt = 2
debug = false   # 开启debug模式，会自动收集客户端的截图，保存在log/img下

[BDO]
window_title = "黑色沙漠 - 436279"  # 黑色沙漠窗口的名称，每次版本更新需要更改
window_class = "BlackDesertWindowClass"
window_title_bar_height = 30    # 窗口标题栏的高度，无边框或全屏设置为0

[GM]
check_cool_time = 1800      # GM督查的时间间隔
chat_color = [[50, 55, 106], [77, 190, 255]]  # GM私聊时特殊字体的颜色
find_pix_max_count = 500    # 检测超过该阈值则触发GM督查警报

[model]
onnx_file_path = "data/onnx/20230215.onnx"  # 模型文件
classes_id_file_path = "data/onnx/class_20230215.txt"   # 标签文件