# Form implementation generated from reading ui file 'designer\app.ui'
#
# Created by: PyQt6 UI code generator 6.4.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from control.logCtrl import LogCtrl
from control.opCtrl import OpCtrl


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(907, 681)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")

        # 日志控件
        self.init_log_ctrl()

        # 操作控件
        self.init_op_ctrl()

        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 907, 22))
        self.menubar.setObjectName("menubar")
        self.configMenu = QtWidgets.QMenu(parent=self.menubar)
        self.configMenu.setObjectName("configMenu")
        self.aboutMenu = QtWidgets.QMenu(parent=self.menubar)
        self.aboutMenu.setObjectName("aboutMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoadConfig = QtGui.QAction(parent=MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/load.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionLoadConfig.setIcon(icon1)
        self.actionLoadConfig.setObjectName("actionLoadConfig")
        self.actionSaveConfig = QtGui.QAction(parent=MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pic/save.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionSaveConfig.setIcon(icon2)
        self.actionSaveConfig.setObjectName("actionSaveConfig")
        self.actionGameSetting = QtGui.QAction(parent=MainWindow)
        self.actionGameSetting.setObjectName("actionGameSetting")
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHwndSetting = QtGui.QAction(parent=MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pic/setting.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionHwndSetting.setIcon(icon3)
        self.actionHwndSetting.setObjectName("actionHwndSetting")
        self.configMenu.addAction(self.actionLoadConfig)
        self.configMenu.addAction(self.actionSaveConfig)
        self.configMenu.addAction(self.actionHwndSetting)
        self.aboutMenu.addAction(self.actionGameSetting)
        self.aboutMenu.addAction(self.actionAbout)
        self.menubar.addAction(self.configMenu.menuAction())
        self.menubar.addAction(self.aboutMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "黑沙-格兰威特10年"))
        self.configMenu.setTitle(_translate("MainWindow", "配置"))
        self.aboutMenu.setTitle(_translate("MainWindow", "关于"))
        self.actionLoadConfig.setText(_translate("MainWindow", "加载配置"))
        self.actionSaveConfig.setText(_translate("MainWindow", "保存当前配置"))
        self.actionGameSetting.setText(_translate("MainWindow", "游戏内设置"))
        self.actionAbout.setText(_translate("MainWindow", "本软件"))
        self.actionHwndSetting.setText(_translate("MainWindow", "黑沙句柄设置"))

    def init_op_ctrl(self):
        self.OpCtrl = OpCtrl(self.centralwidget, logCtrl=self.LogCtrl)
        self.gridLayout.addWidget(self.OpCtrl, 0, 0, 1, 1)

    def init_log_ctrl(self):
        self.LogCtrl = LogCtrl(self.centralwidget)
        self.gridLayout.addWidget(self.LogCtrl, 2, 0, 1, 1)
