# Form implementation generated from reading ui file 'designer\GMCheckDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GMCheckDialog(object):
    def setupUi(self, GMCheckDialog):
        GMCheckDialog.setObjectName("GMCheckDialog")
        GMCheckDialog.resize(317, 202)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(GMCheckDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=GMCheckDialog)
        self.label.setStyleSheet("color: rgb(255,0,0)")
        self.label.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.StopButton = QtWidgets.QPushButton(parent=GMCheckDialog)
        font = QtGui.QFont()
        font.setBold(False)
        self.StopButton.setFont(font)
        self.StopButton.setStyleSheet("")
        self.StopButton.setCheckable(False)
        self.StopButton.setDefault(True)
        self.StopButton.setFlat(False)
        self.StopButton.setObjectName("StopButton")
        self.verticalLayout.addWidget(self.StopButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(GMCheckDialog)
        QtCore.QMetaObject.connectSlotsByName(GMCheckDialog)

    def retranslateUi(self, GMCheckDialog):
        _translate = QtCore.QCoreApplication.translate
        GMCheckDialog.setWindowTitle(_translate("GMCheckDialog", "GM检测警报"))
        self.label.setText(_translate("GMCheckDialog", "检测到GM督查，请立即人工介入！"))
        self.StopButton.setText(_translate("GMCheckDialog", "关闭警报"))
