# Form implementation generated from reading ui file 'designer\GameSettingDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(584, 259)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Dialog.setWindowIcon(icon)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.TestGMCheckSCButton = QtWidgets.QPushButton(parent=Dialog)
        self.TestGMCheckSCButton.setAutoDefault(True)
        self.TestGMCheckSCButton.setDefault(True)
        self.TestGMCheckSCButton.setFlat(False)
        self.TestGMCheckSCButton.setObjectName("TestGMCheckSCButton")
        self.verticalLayout.addWidget(self.TestGMCheckSCButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "关于游戏界面设置"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"justify\"><span style=\" font-size:12pt;\">建议客户端保持如下设置:</span></p><p align=\"justify\">- 分辨率：1920 * 1080</p><p align=\"justify\">- windows DPI缩放调至100%</p><p align=\"justify\">- N卡用户建议安装 CUDA 11.4</p><p align=\"justify\">- 游戏内UI主题设置为精品</p><p align=\"justify\">- 游戏内字体请保持为原生繁体</p><p align=\"justify\"><span style=\" font-size:8pt; color:#ff0000;\">- </span><span style=\" font-weight:700; color:#ff5500;\">游戏聊天框请置于游戏左下角，并确保开启公共频道，请务必重视，事关GM督查检测功能是否工作正常</span></p></body></html>"))
        self.TestGMCheckSCButton.setText(_translate("Dialog", "点击测试截图是否能涵盖游戏聊天窗口"))
        self.TestGMCheckSCButton.setShortcut(_translate("Dialog", "Return"))
