# Form implementation generated from reading ui file 'designer\logCtrl.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LogCtrl(object):
    def setupUi(self, LogCtrl):
        LogCtrl.setObjectName("LogCtrl")
        LogCtrl.resize(404, 224)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(LogCtrl)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=LogCtrl)
        self.frame.setStyleSheet("bord: none;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logLevelLabel = QtWidgets.QLabel(parent=self.frame)
        self.logLevelLabel.setObjectName("logLevelLabel")
        self.horizontalLayout.addWidget(self.logLevelLabel)
        self.LogLevelComboBox = QtWidgets.QComboBox(parent=self.frame)
        self.LogLevelComboBox.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.LogLevelComboBox.setObjectName("LogLevelComboBox")
        self.LogLevelComboBox.addItem("")
        self.LogLevelComboBox.addItem("")
        self.LogLevelComboBox.addItem("")
        self.LogLevelComboBox.addItem("")
        self.horizontalLayout.addWidget(self.LogLevelComboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.SaveLogButton = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaveLogButton.sizePolicy().hasHeightForWidth())
        self.SaveLogButton.setSizePolicy(sizePolicy)
        self.SaveLogButton.setObjectName("SaveLogButton")
        self.horizontalLayout.addWidget(self.SaveLogButton)
        self.ClearLogButton = QtWidgets.QPushButton(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClearLogButton.sizePolicy().hasHeightForWidth())
        self.ClearLogButton.setSizePolicy(sizePolicy)
        self.ClearLogButton.setObjectName("ClearLogButton")
        self.horizontalLayout.addWidget(self.ClearLogButton)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame)
        self.textBrowser = QtWidgets.QTextBrowser(parent=LogCtrl)
        self.textBrowser.setAutoFillBackground(False)
        self.textBrowser.setStyleSheet("bord:none;")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(LogCtrl)
        self.LogLevelComboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LogCtrl)

    def retranslateUi(self, LogCtrl):
        _translate = QtCore.QCoreApplication.translate
        LogCtrl.setWindowTitle(_translate("LogCtrl", "LogCtrl"))
        self.logLevelLabel.setText(_translate("LogCtrl", "过滤日志"))
        self.LogLevelComboBox.setItemText(0, _translate("LogCtrl", "INFO"))
        self.LogLevelComboBox.setItemText(1, _translate("LogCtrl", "ERROR"))
        self.LogLevelComboBox.setItemText(2, _translate("LogCtrl", "WARNING"))
        self.LogLevelComboBox.setItemText(3, _translate("LogCtrl", "DEBUG"))
        self.SaveLogButton.setText(_translate("LogCtrl", "保存"))
        self.ClearLogButton.setText(_translate("LogCtrl", "清空"))
