# Form implementation generated from reading ui file '/Users/dimon/PersionalProject/BDOSuffering/designer/logCtrl.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LogCtrl(object):
    def setupUi(self, LogCtrl):
        LogCtrl.setObjectName("LogCtrl")
        LogCtrl.resize(558, 445)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(LogCtrl)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(LogCtrl)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.SaveLogButton = QtWidgets.QPushButton(self.frame)
        self.SaveLogButton.setObjectName("SaveLogButton")
        self.horizontalLayout.addWidget(self.SaveLogButton)
        self.ClearLogButton = QtWidgets.QPushButton(self.frame)
        self.ClearLogButton.setObjectName("ClearLogButton")
        self.horizontalLayout.addWidget(self.ClearLogButton)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame)
        self.textBrowser = QtWidgets.QTextBrowser(LogCtrl)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(LogCtrl)
        QtCore.QMetaObject.connectSlotsByName(LogCtrl)

    def retranslateUi(self, LogCtrl):
        _translate = QtCore.QCoreApplication.translate
        LogCtrl.setWindowTitle(_translate("LogCtrl", "LogCtrl"))
        self.SaveLogButton.setText(_translate("LogCtrl", "保存"))
        self.ClearLogButton.setText(_translate("LogCtrl", "清空日志"))
