# Form implementation generated from reading ui file '/Users/dimon/PersionalProject/BDOSuffering/designer/op.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OpCtrl(object):
    def setupUi(self, OpCtrl):
        OpCtrl.setObjectName("OpCtrl")
        OpCtrl.resize(464, 182)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(OpCtrl)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.StartPauseButton = QtWidgets.QPushButton(OpCtrl)
        self.StartPauseButton.setObjectName("StartPauseButton")
        self.horizontalLayout.addWidget(self.StartPauseButton)
        self.EndButton = QtWidgets.QPushButton(OpCtrl)
        self.EndButton.setObjectName("EndButton")
        self.horizontalLayout.addWidget(self.EndButton)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(OpCtrl)
        QtCore.QMetaObject.connectSlotsByName(OpCtrl)

    def retranslateUi(self, OpCtrl):
        _translate = QtCore.QCoreApplication.translate
        OpCtrl.setWindowTitle(_translate("OpCtrl", "Form"))
        self.StartPauseButton.setText(_translate("OpCtrl", "开始 F10"))
        self.EndButton.setText(_translate("OpCtrl", "结束 F11"))
